apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: test-lock-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue-test-locks
spec:
  namespaceSelector: {} # Matches all namespaces
  resourceGroups:
  - coveredResources:
    - "test-locks/slurm"
    - "test-locks/ml-slurm"
    - "test-locks/slurm-gcp-v6-rocky8"
    - "test-locks/hpc-build-slurm-image"
    - "test-locks/hpc-enterprise-slurm"
    - "test-locks/hcls"
    - "test-locks/a2-highgpu"
    - "test-locks/gke-a2-highgpu-kueue-onspot"
    - "test-locks/a3-ultragpu"
    - "test-locks/a3-highgpu"
    - "test-locks/a3-megagpu"
    - "test-locks/gke-a3-megagpu-onspot"
    - "test-locks/ml-a3-highgpu-onspot-slurm"
    - "test-locks/gke-a3-ultragpu-onspot"
    - "test-locks/gke-a3-highgpu-onspot"
    - "test-locks/ml-a3-ultragpu-onspot-slurm"
    - "test-locks/ml-a3-ultragpu-onspot-jbvms"
    - "test-locks/a4-highgpu"
    - "test-locks/gke-a4-onspot"
    - "test-locks/a4x"
    - "test-locks/gke-a4x"
    - "test-locks/ml-a4-highgpu-onspot-slurm"
    - "test-locks/ml-gke-e2e"
    - "test-locks/ml-gke"
    - "test-locks/g4-standard"
    - "test-locks/ml-g4-onspot-slurm"
    - "test-locks/ml-a4x-highgpu-slurm"
    - "test-locks/ml-a3-megagpu-onspot-slurm"
    - "test-locks/h4d"
    - "test-locks/h4d-vm"
    - "test-locks/gke-h4d-onspot"
    - "test-locks/ml-h4d-onspot-slurm"
    - "test-locks/tpu-v6e"
    - "test-locks/gke-tpu-v6e"
    - "test-locks/gke-g4-onspot"
    - "test-locks/ansible-vm"
    - "test-locks/batch-mpi"
    - "test-locks/crd-ubuntu"
    - "test-locks/crd"
    - "test-locks/e2e"
    - "test-locks/gke-inactive-reservation"
    - "test-locks/gke-managed-hyperdisk"
    - "test-locks/gke-storage"
    - "test-locks/gke"
    - "test-locks/htc-slurm"
    - "test-locks/htcondor"
    flavors:
    - name: test-lock-flavor
      resources:
      - name: test-locks/slurm
        nominalQuota: 5
      - name: test-locks/ml-slurm
        nominalQuota: 1
      - name: test-locks/slurm-gcp-v6-rocky8
        nominalQuota: 1
      - name: test-locks/hpc-build-slurm-image
        nominalQuota: 1
      - name: test-locks/hpc-enterprise-slurm
        nominalQuota: 1
      - name: test-locks/hcls
        nominalQuota: 1
      - name: test-locks/a2-highgpu
        nominalQuota: 1
      - name: test-locks/gke-a2-highgpu-kueue-onspot
        nominalQuota: 1
      - name: test-locks/a3-ultragpu
        nominalQuota: 1
      - name: test-locks/a3-highgpu
        nominalQuota: 1
      - name: test-locks/a3-megagpu
        nominalQuota: 1
      - name: test-locks/gke-a3-megagpu-onspot
        nominalQuota: 1
      - name: test-locks/ml-a3-highgpu-onspot-slurm
        nominalQuota: 1
      - name: test-locks/gke-a3-ultragpu-onspot
        nominalQuota: 1
      - name: test-locks/gke-a3-highgpu-onspot
        nominalQuota: 1
      - name: test-locks/ml-a3-ultragpu-onspot-slurm
        nominalQuota: 1
      - name: test-locks/ml-a3-ultragpu-onspot-jbvms
        nominalQuota: 1
      - name: test-locks/a4-highgpu
        nominalQuota: 1
      - name: test-locks/gke-a4-onspot
        nominalQuota: 1
      - name: test-locks/a4x
        nominalQuota: 1
      - name: test-locks/gke-a4x
        nominalQuota: 1
      - name: test-locks/ml-a4-highgpu-onspot-slurm
        nominalQuota: 1
      - name: test-locks/ml-gke-e2e
        nominalQuota: 1
      - name: test-locks/ml-gke
        nominalQuota: 1
      - name: test-locks/g4-standard
        nominalQuota: 1
      - name: test-locks/ml-g4-onspot-slurm
        nominalQuota: 1
      - name: test-locks/ml-a4x-highgpu-slurm
        nominalQuota: 1
      - name: test-locks/ml-a3-megagpu-onspot-slurm
        nominalQuota: 1
      - name: test-locks/h4d
        nominalQuota: 1
      - name: test-locks/h4d-vm
        nominalQuota: 1
      - name: test-locks/gke-h4d-onspot
        nominalQuota: 1
      - name: test-locks/ml-h4d-onspot-slurm
        nominalQuota: 1
      - name: test-locks/tpu-v6e
        nominalQuota: 1
      - name: test-locks/gke-tpu-v6e
        nominalQuota: 1
      - name: test-locks/gke-g4-onspot
        nominalQuota: 1
      - name: test-locks/ansible-vm
        nominalQuota: 1
      - name: test-locks/batch-mpi
        nominalQuota: 1
      - name: test-locks/crd-ubuntu
        nominalQuota: 1
      - name: test-locks/crd
        nominalQuota: 1
      - name: test-locks/e2e
        nominalQuota: 1
      - name: test-locks/gke-inactive-reservation
        nominalQuota: 1
      - name: test-locks/gke-managed-hyperdisk
        nominalQuota: 1
      - name: test-locks/gke-storage
        nominalQuota: 1
      - name: test-locks/gke
        nominalQuota: 1
      - name: test-locks/htc-slurm
        nominalQuota: 1
      - name: test-locks/htcondor
        nominalQuota: 1
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: local-queue-test-locks
  namespace: default
spec:
  clusterQueue: cluster-queue-test-locks
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: emergency-hotfix-priority
value: 10000
globalDefault: false
description: "Highest priority for emergency hotfix PR tests."