apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: test-lock-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue-test-locks
spec:
  namespaceSelector: {} # Matches all namespaces
  resourceGroups:
  - coveredResources:
    - "test-locks/slurm"
    - "test-locks/slurm-gcp-v6-rocky8"
    - "test-locks/a3-ultragpu"
    - "test-locks/gke-a3-ultragpu-onspot"
    - "test-locks/ml-a3-ultragpu-onspot-slurm"
    flavors:
    - name: test-lock-flavor
      resources:
      - name: test-locks/slurm
        nominalQuota: 5
      - name: test-locks/slurm-gcp-v6-rocky8
        nominalQuota: 1
      - name: test-locks/a3-ultragpu
        nominalQuota: 1
      - name: test-locks/gke-a3-ultragpu-onspot
        nominalQuota: 1
      - name: test-locks/ml-a3-ultragpu-onspot-slurm
        nominalQuota: 1
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: local-queue-test-locks
  namespace: default
spec:
  clusterQueue: cluster-queue-test-locks
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: daily-test-priority
value: 500
globalDefault: false
description: "Standard priority for automated daily integration tests."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pr-test-priority
value: 1000
globalDefault: true
description: "High priority for PR validation tests."